### ISSUE TITLE
Missing Python 3.5/3.6 build for Windows (vc14)

### ISSUE THREAD

**Issue by snorfalorpagus** [conda-forge/lp_solve-feedstock#4]
It looks like this feedstock isn't doing builds for Windows + Python 3.6:

https://anaconda.org/conda-forge/lp_solve/files
https://ci.appveyor.com/project/conda-forge/lp-solve-feedstock/branch/master

I had a similar attempt at a feedstock for lpsolve here: https://github.com/conda-forge/staged-recipes/pull/2501/files

I'll have a look through and see if there is anything worth porting.

@jschueller / @mictadlo, any idea why this build config is missing? The recipe looks sensible to me.

**Comment by jschueller** [comment]
thats only a lib, there are no bindings, you can checkout cvxopt

**Comment by jschueller** [comment]
I see, there's no vc14 libs, the title was misleading.

**Comment by jschueller** [comment]
fixed in #5
